### ISSUE TITLE
To merge two or more HLL sets

### ISSUE THREAD

**Issue by yashk** [MLnick/hive-udf#2]
We know that two or more HLL sets can be merged to  get cardinality of larger set , for example if we have 31 HLL sets of  unique visitor count each for one day , then we can merge them to get unique visitor count for a month. can this be supported by this UDAF ?

**Comment by abramsm** [comment]
Yes.    

## 

Matt Abrams

**Comment by MLnick** [comment]
To provide a bit more detail - assuming you've created a column `approx` as `struct {type string; cardinality bigint; binary binary}`, and did something like `select approx_distinct(col) as approx from ...`, then each row will contain the HLL structure for the relevant day. You can the do `select approx_distinct(approx).cardinality from APPROX_TABLE ...` to get the cardinality of the merged HLL structures.

**Comment by yashk** [comment]
Thanks @abramsm @MLnick will try and update

**Comment by moizarafat** [comment]
Do you plan to add functionality for intersection / minus between two sets.

**Comment by abramsm** [comment]
No.  HyperLogLog intersection is a bit tricky and requires that the
intersection is performed on two or more instances that have
certain characteristics.  Even though it is not implemented in the core
library it is trivial to perform the intersection.  Here is a thread on the
stream-lib mailing list on this topic:

https://groups.google.com/forum/?fromgroups=#!searchin/stream-lib-user/intersection/stream-lib-user/LKagmkKYA14/ffPzy55O6JwJ

Cheers,
Matt

**Comment by yashk** [comment]
we tried the merge and it is working , thanks @MLnick @abramsm
