### ISSUE TITLE
 How to make the UDAF run with old version of Hive  ?

### ISSUE THREAD

**Issue by moizarafat** [MLnick/hive-udf#4]
Hi,

Had a question

a) What changes will be required to run this UDAF with older version of hive say 0.7

Thanks

**Comment by MLnick** [comment]
Hi
Unfortunately I don't know offhand as I no longer really use Hive day-to-day. Have you tried it with 0.7? Does it throw errors?

**Comment by moizarafat** [comment]
Hi,

Some one already had that issue raised i think. "java.lang.NoSuchFieldError: writableBinaryObjectInspector while running the udaf " .  I think its because there is no Binary Data type in hive 0.7. I was wondering if there is a workaround available.

**Comment by MLnick** [comment]
Ah

It would be possible to serialize the binary blob to say Base64 string. That would require code changes to the UDAF appropriately.

Any chance you can upgrade to newer Hive version? :)

—

**Comment by moizarafat** [comment]
Ok . Our prod environment is Hive 0.7 and we are still 4-5 months away from upgrade. We used the UDAF in our Test environment and worked great. we wanted to start using it in prod, but got stuck with 0.7 issue :(
